# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022-2023 Dell Inc, or its subsidiaries.
---
version: '3.7'

services:
  vpn-server:
    image: strongx509/strongswan:5.9.13
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
    stdin_open: true
    tty: true
    volumes:
      - ./conf/server:/etc/swanctl
      - ./conf/strongswan-server.conf:/etc/strongswan.conf
      - /var/run
    networks:
      internet:
        ipv4_address: 192.168.200.210
      intranet:
        ipv4_address: 10.1.0.2
    command: './charon'

  vpn-client:
    image: strongx509/strongswan:5.9.13
    depends_on:
      - vpn-server
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
    stdin_open: true
    tty: true
    volumes:
      - ./conf/client:/etc/swanctl
      - ./conf/strongswan-client.conf:/etc/strongswan.conf
      - /var/run
    networks:
      internet:
        ipv4_address: 192.168.200.200
    command: './charon'

  opi-security-server:
    build:
      context: .
    depends_on:
      - vpn-client
      - redis
    volumes_from:
      - vpn-client:rw
    networks:
      - internet
      - intranet
    command: /opi-vici-bridge -port=50151
    healthcheck:
      test: grpcurl -plaintext localhost:50151 list || exit 1

  redis:
    image: redis:7.2.3-alpine3.18
    networks:
      - internet
      - intranet
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]

  opi-test:
    image: ghcr.io/opiproject/godpu:main@sha256:780c19cff0310798f57cf72cfeb01c01c43e6fce8c854e5ec4c6c368fb4929c5
    network_mode: service:vpn-server
    depends_on:
      opi-security-server:
        condition: service_healthy
    command: ipsec test --addr=opi-security-server:50151 --pingaddr=10.3.0.1


networks:
  internet:
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24
  intranet:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16
