---
name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2.4.1
      
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the GH Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    # Workaround: https://github.com/docker/build-push-action/issues/461
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@2dd22fa31c04297d369158eb483250f578504a9f

    - name: Start containers
      run: docker-compose up -d

    - name: Logs
      if: failure()
      run: docker-compose logs

    - name: Stop containers
      if: always()
      run: docker-compose down

    - name: Run Tests
      run: |
        set -x
        docker-compose up --build --force-recreate --detach
        docker-compose ps
        name=$(docker-compose ps | grep opi-security-client | awk '{print $1}')
        rc=$(docker wait "${name}")
        if [ "${rc}" != "0" ]; then
            echo "opi-security-client failed:"
            docker logs "${name}"
            exit 1
        fi
        grpc_cli=(docker run --network=opi-strongswan-bridge_internet --rm namely/grpc-cli)
        "${grpc_cli[@]}" ls opi-security-server:50151
        "${grpc_cli[@]}" ls opi-security-server:50151 opi_api.security.v1.IPsec -l
        "${grpc_cli[@]}" ls opi-security-server:50151 opi_api.security.v1.IPsec.IPsecVersion -l
        "${grpc_cli[@]}" ls opi-security-server:50151 opi_api.security.v1.IPsec.IPsecStats -l
        "${grpc_cli[@]}" ls opi-security-server:50151 opi_api.security.v1.IPsec.IPsecInitiate -l
        "${grpc_cli[@]}" ls opi-security-server:50151 opi_api.security.v1.IPsec.IPsecTerminate -l
        "${grpc_cli[@]}" ls opi-security-server:50151 opi_api.security.v1.IPsec.IPsecRekey -l
        "${grpc_cli[@]}" ls opi-security-server:50151 opi_api.security.v1.IPsec.IPsecListSas -l
        "${grpc_cli[@]}" ls opi-security-server:50151 opi_api.security.v1.IPsec.IPsecListConns -l
        "${grpc_cli[@]}" ls opi-security-server:50151 opi_api.security.v1.IPsec.IPsecListCerts -l
        "${grpc_cli[@]}" ls opi-security-server:50151 opi_api.security.v1.IPsec.IPsecLoadConn -l
        "${grpc_cli[@]}" ls opi-security-server:50151 opi_api.security.v1.IPsec.IPsecUnloadConn -l

    - name: Logs
      if: always()
      run: docker-compose logs

    - name: Stop containers
      if: always()
      run: docker-compose down
